// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShortalkB2.Service.Context;

#nullable disable

namespace ShortalkB2.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ShortalkB2.Models.GameModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BuzzWords")
                        .HasColumnType("TEXT");

                    b.Property<string>("GamePhase")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfRounds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OnePointWord")
                        .HasColumnType("TEXT");

                    b.Property<bool>("OnePointWordHasBeenSaid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OnePointWords")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerA1")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerA2")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerA3")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerA4")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerA5")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerB1")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerB2")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerB3")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerB4")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerB5")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReadyStatusA1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReadyStatusA2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReadyStatusA3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReadyStatusA4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReadyStatusA5")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReadyStatusB1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReadyStatusB2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReadyStatusB3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReadyStatusB4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReadyStatusB5")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoomName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkippedWords")
                        .HasColumnType("TEXT");

                    b.Property<string>("Speaker")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamAScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamBScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThreePointWord")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ThreePointWordHasBeenSaid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThreePointWords")
                        .HasColumnType("TEXT");

                    b.Property<int>("Time")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("GameInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
